### ISSUE TITLE
Mission-generated allies not displaying

### ISSUE THREAD

**Issue by Cdndragoon610** [GlowPuff/ImperialCommander2#36]
I just finished working through the Torn Asunder custom campaign and I wanted to post a couple of bugs associated with it, that may also be applicable to the larger project.  The first one is that I can select an ally to bring with me on a mission, but if the mission generates an ally, (Alliance Rangers, for example) then my selected Ally appears but the mission-generated one does not.  

In Strike Force Xesh, for example, I didn't know I had Rebel Troopers with me until an Imperial action targeted them.  My workaround was to play the mission-generated ally when I wanted, then hitting the Imperial turn button to flip the action back to the AI.  But there should be a pop-up for missions like this that prompt the player to deploy the Mission-generated allies at the beginning of the mission.

I'd have to go through all the side missions to see which ones have mission-generated Allies, but wanted to put it on the developer radar in case this is a known bug.

**Comment by GlowPuff** [comment]
Nice find, thank you!

**Comment by GlowPuff** [comment]
I'm unable to reproduce this problem.  For my testing scenario, I brought an Ally along in a mission (Chewy).  Then I had the test mission add more Allies by:
- Ally Deployment event action (Han)
- Fixed Ally on startup (Luke, through Mission Properties)
They all appeared in the mission, and the event action popped up a notice about Han being deployed:
![allies](https://user-images.githubusercontent.com/22311140/232176875-cca07b96-a8d0-4734-8424-ddb0036c4eb8.png)
Only one thing will stop a group from deploying: if it's already deployed.  This goes for any deployable group - allies, villains, imperials.  It's possible the custom mission already had this card deployed, so it silently skipped it when told to deploy it again.

**Comment by Cdndragoon610** [comment]
Ok, so here's what I did this morning to verify if I had the issue properly described.  IT might be as simple as a script prompt to get the player to add a second Ally

Go to Saga and start a new mission - select Strike Force Xesh, as it has Alliance Rangers included in the mission.  
Select four heros and an Ally - for my purposes, I added Obi Wan.
Start the mission and it will have the four heros, Obi Wan but no Alliance Rangers present and no prompt to deploy them as allies.

**Comment by Cdndragoon610** [comment]
I tried it with Home Invasion, the Ahsoka Tano mission, and got a slight different result.
I selected the same four heros and added Obi Wan as an Ally.
When I started the mission, it went through the initial Imperial deployment phase and prompted me to deploy Ahsoka - but didn't add her to the left hand column of player assets.  It had my four heros and Obi Wan, but the first player turn began without Ahsoka as a selectable turn.

**Comment by Noldorion** [comment]
Hey,

I can't check it right now, but yan you try something? On the left, there's only room for 5 icons. When more Rebel groups get deployed, they are not immediately visible and you need to scroll down on the left to see them. I'm very sure this is the case with Ahsoka, and you might try it with Strike Force Xesh, too.

**Comment by Cdndragoon610** [comment]
Great catch - yes, for the Ahsoka mission, you can scroll down to find her.  The five icons fit so perfectly on the left side that there's no clue to scroll down to find her, but she is there!  Maybe a small arrow in the UI to indicate there's more below would help in cases where there are more than 5 player assets?

For Strike Force Xesh, the Alliance Rangers still don't appear, though.  I tried both with an Ally and without, but no joy.

**Comment by GlowPuff** [comment]
Nice catch, that's gotta be it!  I changed the scroll viewer so the scrollbars are visible when there is overflow (same for the Imperial side):
![scrollbar](https://user-images.githubusercontent.com/22311140/233204060-5e199649-c79e-4cd1-962f-7698a7f2c2e0.png)
